extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/typescript'
  - 'prettier'

env:
  es6: true
  node: true

globals:
  chai: 'readonly'
  expect: 'readonly'

ignorePatterns: ['lib', 'coverage']

parser: '@typescript-eslint/parser'

parserOptions:
  project: 'tsconfig.json'
  sourceType: 'module'

plugins:
  - '@typescript-eslint'

settings:
  'import/resolver':
    typescript:
      alwaysTryTypes: true,
      project: 'tsconfig.json'

rules:
  'global-require': 'off'

  'no-empty': ['error', {allowEmptyCatch: true}]
  'no-param-reassign': ['error', {props: false}]
  'no-underscore-dangle': 'off'
