bracketSpacing: false
endOfLine: lf
jsxSingleQuote: true
semi: true
singleQuote: true
tabWidth: 2
overrides:
  - files:
      - '*.json'
    options:
      singleQuote: false
      trailingComma: none
  - files:
      - '.vscode/*.json'
    options:
      tabWidth: 4
  - files:
      - '*.md'
    options:
      singleQuote: false
