name: CI

on:
  push:
    branches: [main, 'renovate/**']
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm
      env:
        NODE_VERSION: 18.15.0 # renovate: datasource=npm depName=node versioning=node
    - run: npm ci --ignore-scripts
    - run: npm run build --if-present
    - run: npm run lint --if-present
    - run: npm test
