name: CI

on:
  push:
    branches: [main, 'renovate/**']
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
        env:
          NODE_VERSION: 18.17.1 # renovate: datasource=npm depName=node versioning=node
      - run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm run check-format
      - run: npm run lint
      - run: npm test
