name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main, 'renovate/**']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          cache: pnpm
          node-version-file: '.node-version'
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm run build
      - run: pnpm run check-format
      - run: pnpm run lint
      - run: pnpm test
