name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main, 'renovate/**']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          cache: pnpm
          node-version-file: '.node-version'
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm run build
      - run: pnpm run check-format
      - run: pnpm run lint
      - run: pnpm test
