---
# Renovate this repository if Renovate-specific tasks are checked, if this workflow file or the Renovate configuration file is changed, or if dispatched.
name: Renovate

'on':
  issues:
    types: [edited]
  pull_request:
    types: [edited]
  push:
    branches: ['**']
  workflow_dispatch:
    inputs:
      print-config:
        description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
        required: false
        type: boolean
        default: false
  workflow_run:
    workflows: ['Main']
    branches: ['main']
    types: ['completed']

jobs:
  renovate:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    name: Renovate
    secrets:
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      APPLICATION_PRIVATE_KEY: ${{ secrets.APPLICATION_PRIVATE_KEY }}
    uses: bfra-me/.github/.github/workflows/renovate.yaml@4b1dd2e7e4976e1b2bab93a1a25bf0b3a6ee0850 # v2.0.2
    with:
      print_config: ${{ inputs.print-config || false }}
